### ISSUE TITLE
Doesnt find anything?

### ISSUE THREAD

**Issue by thepenguinthatwants** [JakeStanger/Rofi_MPD#16]
Hi I installed this from aur package.

By selecting rofi-mpd it opens up a  menu with
Select artist:

and its empty.. pressing enter etc doesnt show me informations about anything.

All the music files are in ~/Music
and mpd should work on 6600 not sure how to debug this.

**Comment by JakeStanger** [comment]
> and mpd should work

Is MPD definitely working with a populated database? 
Run `mpc list artist` and check a list of artists come back if you're not sure.

**Comment by thepenguinthatwants** [comment]
Oh it doesnt give anything back . I guess I need to configure mpc separately?

exists in my mpd.conf and ~/.config/rofi-mpd/config.toml

music_directory    "~/Music"

also mpc next brings me to another song in the ncmpcpp list that I added.

**Comment by JakeStanger** [comment]
`mpc` is just the most basic MPD client. This is also an MPD client, so if neither this nor MPC are finding anything it would suggest that MPD is not running/properly configured.

I'm going to close this for now as it sounds like it's not an issue with this program. Feel free to reply if that changes.
