### ISSUE TITLE
#! shebang at the beginning of the file?

### ISSUE THREAD

**Issue by rubdos** [JakeStanger/Rofi_MPD#2]
I'm here again, mind adding `#!/usr/bin/env python3` to the beginning of `main.py`?

edit: or whatever python version you use :-)

**Comment by rubdos** [comment]
By the way, feel free to ping me on freenode or something.

**Comment by rubdos** [comment]
FYI: https://aur.archlinux.org/packages/rofi-mpd-git/

After this bugfix, `rofi-mpd` should just run!

**Comment by JakeStanger** [comment]
Python 3 is correct. I'm busy at the moment but if you submit a PR I'll merge it when I can.

And a huge thanks, this is super cool!
