### ISSUE TITLE
Suggestion : Case insensitve search

### ISSUE THREAD

**Issue by monsieurh** [JakeStanger/Rofi_MPD#6]
I would love to have the search method being insensive to case and/or with fuzzy search.

**Comment by JakeStanger** [comment]
I will have to look into how Rofi handles this. You may already be able to do it with `--args` and I know rofi has a case insensitive setting, although I couldn't get this to work myself.

**Comment by JakeStanger** [comment]
f02f06e disables case-sensitivity by default. You can also pass an `-i` flag to re-enable case sensitivity. 

I also discovered you can toggle case sensitivity from inside Rofi with the grave key.

This commit also fixes Rofi command line arguments not being passed correctly, which I discovered in the process.
