### ISSUE TITLE
Date can be a list

### ISSUE THREAD

**Issue by EgZvor** [JakeStanger/Rofi_MPD#7]
```
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    'epoch': get_album_release_epoch(song_data=song),
  File "main.py", line 77, in get_album_release_epoch
    if date.isnumeric():
AttributeError: 'list' object has no attribute 'isnumeric'
```

**Comment by JakeStanger** [comment]
Are you able to get me the track date causing this crash? Just a `print(date)` on the line above would be sufficient. I'd like to know why a date would be a list.

**Comment by EgZvor** [comment]
It looks like this in ncmpcpp
![image](https://user-images.githubusercontent.com/11237935/46547795-bd0af000-c8d5-11e8-92d7-3bdd99ba72c4.png)

**Comment by EgZvor** [comment]
```
import json

from mpd import MPDClient


client = MPDClient()
client.connect('localhost', '6600')

library = client.listallinfo()

print(json.dumps([
    song for song in library
    if isinstance(song.get('date'), list)][0], indent=2
))
```
```
(.env) ➜ ~/repos/Rofi_MPD (master) ✗ python showdoubledate.py
{
  "file": "Gorillaz - The Now Now/01 - Humility (feat. George Benson).mp3",
  "last-modified": "2018-07-25T18:41:25Z",
  "time": "198",
  "duration": "197.982",
  "artist": "Gorillaz",
  "albumartist": "Gorillaz",
  "title": "Humility (feat. George Benson)",
  "album": "The Now Now",
  "track": "1",
  "date": [
    "2018",
    "2018"
  ],
  "genre": "Alternative",
  "composer": "Gorillaz",
  "disc": "1"
}
```

**Comment by EgZvor** [comment]
I guess this is relevant
https://github.com/Mic92/python-mpd2/blob/master/examples/multitags.py

**Comment by JakeStanger** [comment]
This is all very helpful, thank you very much. Also your rice is very pretty.

 ae9df0b should serve as a fix for now. Let me know if this works or if you want any different behavior.

**Comment by EgZvor** [comment]
That's fine (it's what I did too anyway). Knowing what this double date means would probably help to decide what to do with it in the future.
